ListaDeTarefas/Controllers/TarefaUserController.cs
using ListaDeTarefas.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace ListaDeTarefas.Controllers
{
    public class TarefaUserController : Controller
    {
        private readonly ListaTarefaDBContext _context;

        public TarefaUserController(ListaTarefaDBContext context)
        {
            _context = context;
        }

        [HttpGet("/TarefaUser/{id}/{situacao?}/{prioridade?}")]
        public async  Task<IActionResult> Index(int id, int? situacao, int? prioridade)
        {
            var TarefaPorUsuario = _context.Tarefas.Where(t => t.FkUserTarefa == id);         
            if (situacao != null && prioridade != null)
            {       
                return View(_context.Tarefas.Where(
                    table => ((table.Prioridade == prioridade && table.Situacao == situacao) && (table.FkUserTarefa == id))));
            }
            if (situacao != null || prioridade != null)
            {
                return View(_context.Tarefas.Where(
                    table => ((table.Prioridade == prioridade || table.Situacao == situacao) && (table.FkUserTarefa == id))));
            }
            return View(TarefaPorUsuario) ;
        }

        [HttpGet("/TarefaUser/NovaTarefa/{id}")]
        public IActionResult NovaTarefa(int id)
        {
            ViewData["id"] = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult NovaTarefa(int id, Tarefa tarefa) 
        {
            if (ModelState.IsValid) 
            {
                _context.Tarefas.Add(tarefa);
                _context.SaveChanges();
                return RedirectToAction("Index", new{id});
            }
            return NotFound();
        }

        [HttpGet("/TarefaUser/AtualizarTarefas/{id?}/{idTarefa?}")]
        public IActionResult AtualizarTarefas(int id, int idTarefa) 
        {
            var tarefa = _context.Tarefas.Where(t => t.TarefasId == idTarefa && t.FkUserTarefa == id).FirstOrDefault();
            ViewData["idTarefa"] = tarefa.TarefasId;
            return View(tarefa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AtualizarTarefas(int id, Tarefa tarefa) 
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Tarefas.Update(tarefa);
                    _context.SaveChanges();
                    return RedirectToAction("Index", new { id });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TarefaExist(tarefa.TarefasId))
                    {
                        return NotFound();
                    }
                    else 
                    {
                        throw;
                    }
                }                
            }
            return View();
        }

		[HttpGet("/TarefaUser/ExcluirTarefa/{id}/{idTarefa}")]
		public IActionResult ExcluirTarefa(int id, int idTarefa)
		{
			var confirm = _context.Tarefas.FirstOrDefault(x => x.TarefasId == idTarefa && x.FkUserTarefa == id);
            ViewData["idTarefa"] = confirm.TarefasId;
			return View(confirm);
		}

		[HttpPost, ActionName("ExcluirTarefa")]
		[ValidateAntiForgeryToken]
		public IActionResult ConfirmExclusaoTarefa(int id, int idTarefa)
		{
			if (ModelState.IsValid)
			{
                var confirm = _context.Tarefas.FirstOrDefault(x => x.TarefasId == idTarefa && x.FkUserTarefa == id);

                if (confirm != null)
				{
					_context.Tarefas.Remove(confirm);
					_context.SaveChanges();
					return RedirectToAction("Index", new { id });
                }        
				return RedirectToAction("Index", new { id });
			}
            return NotFound();
		}

        private bool TarefaExist(int id)
        {
            return _context.Tarefas.Any(e => e.TarefasId == id);
        }
    }
}

ListaDeTarefas/Views/TarefaUser/AtualizarTarefas.cshtml
@model ListaDeTarefas.Models.Tarefa

@{
}


<h2>Atulizar Tarefa</h2>

<div class="row">
    <div>
        <form asp-action="AtualizarTarefas" method="post">
            <input type="hidden" asp-for="TarefasId" />
            <input type="hidden" asp-for="FkUserTarefa">
            <div class="form-group">
                <label asp-for="NomeTarefa" class="control-label">Tarefa</label>
                <input asp-for="NomeTarefa" class="form-control">
            </div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label">Descricao</label>
                <input asp-for="Descricao" class="form-control">
            </div>

            <div class="form-group">
                <label asp-for="Inicio" class="control-label">Inicio</label>
                <input asp-for="Inicio" id="DataInicio" type="date" class="form-control">
                <script></script>
            </div>

            <div class="form-group">
                <label asp-for="Fim" class="control-label">Fim</label>
                <input asp-for="Fim" type="date" id="DataFinal" class="form-control">
            </div>

            <div class="form-group">
                <select name="situacao" class="form-control">
                    <option value=1>Ativo</option>
                    <option value=0>Inativo</option>
                </select>
            </div>

            <div class="form-group">
                <select name="Prioridade" class="form-control">
                    <option value=1>Alta</option>
                    <option value=0>Baixa</option>
                </select>
            </div>

            <input type="submit" value="Atulizar" class="btn btn-info" />

        </form>

        <a asp-action="Index" class="btn btn-link">Voltar</a>

    </div>

</div>

ListaDeTarefas/Views/TarefaUser/ExcluirTarefa.cshtml
@model ListaDeTarefas.Models.Tarefa

@{
    var idTarefa = ViewData["idTarefa"];
}

<h2>Excluir</h2>

<div class="row">
    @Html.DisplayFor(Model => Model.TarefasId)
    @Html.DisplayFor(Model => Model.NomeTarefa)
    @Html.DisplayFor(Model => Model.Descricao)
    @Html.DisplayFor(Model => Model.Inicio)
    @Html.DisplayFor(Model => Model.Fim)
    @Html.DisplayFor(Model => Model.Situacao)
</div>

<form asp-action="ExcluirTarefa" method="post">
    <input type="hidden" asp-for="@idTarefa" />
    <input type="submit" value="ConfirmExclusaoTarefa"  class="btn btn-danger" />
</form>

ListaDeTarefas/Views/TarefaUser/Index.cshtml
@model IEnumerable<ListaDeTarefas.Models.Tarefa>
@{
    var id = ViewData["id"];
}

<div class="container">
    <form asp-controller="TarefaUser" asp-action="Index" method="get">
        <div class="control-label">

            <select name="situacao" class="control-label">
                <option value=""></option>
                <option value=1>Ativo</option>
                <option value=0>Inativo</option>
            </select>

            <select name="prioridade" class="control-label">
                <option value=""></option>>
                <option value=1>Alta</option>
                <option value=0>Baixa</option>
            </select>

            <input type="submit">
        </div>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>
                    id
                </th>
                <th>
                    Nome
                </th>
                <th>
                    Descricão
                </th>
                <th>
                    Inicio
                </th>
                <th>
                    Fim
                </th>
                <th>
                    Situação
                </th>
                <th>
                    Prioridade
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @id
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.NomeTarefa)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.Descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.Inicio.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.Fim.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.DescricaoStatus)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.DescricaoPrioridade)
                    </td>
                    <td>
                        <a asp-action="AtualizarTarefas" asp-route-id="@item.FkUserTarefa" asp-route-idTarefa="@item.TarefasId" class="btn btn-info">Atualizar</a>
                        <a asp-action="ExcluirTarefa" asp-route-id="@item.FkUserTarefa" asp-route-idTarefa="@item.TarefasId" class="btn btn-danger">Excluir</a>

                    </td>
                </tr>


            }
        </tbody>
    </table>
</div>

@foreach (var item in Model) 
{
    <a asp-action="NovaTarefa" asp-route-id="@item.FkUserTarefa" class="btn btn-primary">Nova Tarefa</a>
}
    

ListaDeTarefas/Views/TarefaUser/NovaTarefa.cshtml
@model ListaDeTarefas.Models.Tarefa
@{
    var id = ViewData["id"];
}

<h1>Nova Tarefa</h1>

<form asp-action="NovaTarefa" method="post">
    <div class="form-group">
        <label asp-for="NomeTarefa" class="control-label">Tarefa</label>
        <input asp-for="NomeTarefa" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Descricao" class="control-label">Descricao</label>
        <input asp-for="Descricao" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Inicio" class="control-label">Inicio</label>
        <input asp-for="Inicio" id="DataInicio" type="date" class="form-control">
        <script></script>
    </div>

    <div class="form-group">
        <label asp-for="Fim" class="control-label">Fim</label>
        <input asp-for="Fim" type="date" id="DataFinal" class="form-control">
    </div>

    <div class="form-group">
        <select name="situacao" class="form-control">
            <option value=1>Ativo</option>
            <option value=0>Inativo</option>
        </select>
    </div>

    <div class="form-group">
        <select name="Prioridade" class="form-control">
            <option value=1>Alta</option>
            <option value=0>Baixa</option>
        </select>
    </div>

    <div class="form-group">
        <input asp-for="FkUserTarefa" value="@id" type="hidden" class="form-control">
    </div>

    <input type="submit" value="Salvar" class="btn" />
</form>

<a asp-action="Index" class="btn btn-lik">Voltar</a>